import asset from './asset';

export function getImgByName(name) {
    switch (name) {
        case 'asset.tshirt_m_1':
            return asset.tshirt_m_1;
        case 'asset.tshirt_m_2':
            return asset.tshirt_m_2;
        case 'asset.tshirt_m_3':
            return asset.tshirt_m_3;
        case 'asset.tshirt_m_4':
            return asset.tshirt_m_4;
        case 'asset.tshirt_m_5':
            return asset.tshirt_m_5;
        case 'asset.tshirt_m_6':
            return asset.tshirt_m_6;
        case 'asset.tshirt_m_7':
            return asset.tshirt_m_7;
        case 'asset.tshirt_m_8':
            return asset.tshirt_m_8;
        case 'asset.tshirt_m_9':
            return asset.tshirt_m_9;
        case 'asset.tshirt_m_10':
            return asset.tshirt_m_10;
        case 'asset.tshirt_w_1':
            return asset.tshirt_w_1;
        case 'asset.tshirt_w_2':
            return asset.tshirt_w_2;
        case 'asset.tshirt_w_3':
            return asset.tshirt_w_3;
        case 'asset.tshirt_w_4':
            return asset.tshirt_w_4;
        case 'asset.tshirt_w_5':
            return asset.tshirt_w_5;
        case 'asset.tshirt_w_6':
            return asset.tshirt_w_6;
        case 'asset.tshirt_w_7':
            return asset.tshirt_w_7;
        case 'asset.tshirt_w_8':
            return asset.tshirt_w_8;
        case 'asset.tshirt_w_9':
            return asset.tshirt_w_9;
        case 'asset.tshirt_w_10':
            return asset.tshirt_w_10;
        case 'asset.tshirt_w_11':
            return asset.tshirt_w_11;
        case 'asset.tshirt_w_12':
            return asset.tshirt_w_12;
        case 'asset.tshirt_w_13':
            return asset.tshirt_w_13;
        case 'asset.jackets_m_1':
            return asset.jackets_m_1;
        case 'asset.jackets_m_2':
            return asset.jackets_m_2;
        case 'asset.jackets_m_3':
            return asset.jackets_m_3;
        case 'asset.jackets_m_4':
            return asset.jackets_m_4;
        case 'asset.jackets_m_5':
            return asset.jackets_m_5;
        case 'asset.jackets_m_6':
            return asset.jackets_m_6;
        case 'asset.jackets_m_7':
            return asset.jackets_m_7;
        case 'asset.jackets_m_8':
            return asset.jackets_m_8;
        case 'asset.jackets_m_9':
            return asset.jackets_m_9;
        case 'asset.jackets_m_10':
            return asset.jackets_m_10;
        case 'asset.jackets_m_11':
            return asset.jackets_m_11;
        case 'asset.jackets_m_12':
            return asset.jackets_m_12;
        case 'asset.jackets_m_13':
            return asset.jackets_m_13;
        case 'asset.jackets_w_1':
            return asset.jackets_w_1;
        case 'asset.jackets_w_2':
            return asset.jackets_w_2;
        case 'asset.jackets_w_3':
            return asset.jackets_w_3;
        case 'asset.jackets_w_4':
            return asset.jackets_w_4;
        case 'asset.jackets_w_5':
            return asset.jackets_w_5;
        case 'asset.jackets_w_6':
            return asset.jackets_w_6;
        case 'asset.jackets_w_7':
            return asset.jackets_w_7;
        case 'asset.jackets_w_8':
            return asset.jackets_w_8;
        case 'asset.jackets_w_9':
            return asset.jackets_w_9;
        case 'asset.jackets_w_10':
            return asset.jackets_w_10;
        case 'asset.jackets_w_11':
            return asset.jackets_w_11;
        case 'asset.hoodies_m_1':
            return asset.hoodies_m_1;
        case 'asset.hoodies_m_2':
            return asset.hoodies_m_2;
        case 'asset.hoodies_m_3':
            return asset.hoodies_m_3;
        case 'asset.hoodies_m_4':
            return asset.hoodies_m_4;
        case 'asset.hoodies_m_5':
            return asset.hoodies_m_5;
        case 'asset.hoodies_m_6':
            return asset.hoodies_m_6;
        case 'asset.hoodies_m_7':
            return asset.hoodies_m_7;
        case 'asset.hoodies_m_8':
            return asset.hoodies_m_8;
        case 'asset.hoodies_m_9':
            return asset.hoodies_m_9;
        case 'asset.hoodies_m_10':
            return asset.hoodies_m_10;
        case 'asset.hoodies_m_11':
            return asset.hoodies_m_11;
        case 'asset.hoodies_m_12':
            return asset.hoodies_m_12;
        case 'asset.hoodies_w_1':
            return asset.hoodies_w_1;
        case 'asset.hoodies_w_2':
            return asset.hoodies_w_2;
        case 'asset.hoodies_w_3':
            return asset.hoodies_w_3;
        case 'asset.hoodies_w_4':
            return asset.hoodies_w_4;
        case 'asset.hoodies_w_5':
            return asset.hoodies_w_5;
        case 'asset.hoodies_w_6':
            return asset.hoodies_w_6;
        case 'asset.hoodies_w_7':
            return asset.hoodies_w_7;
        case 'asset.hoodies_w_8':
            return asset.hoodies_w_8;
        case 'asset.hoodies_w_9':
            return asset.hoodies_w_9;
        case 'asset.hoodies_w_10':
            return asset.hoodies_w_10;
        case 'asset.hoodies_w_11':
            return asset.hoodies_w_11;
        case 'asset.hoodies_w_12':
            return asset.hoodies_w_12;
        case 'asset.jeans_m_1':
            return asset.jeans_m_1;
        case 'asset.jeans_m_2':
            return asset.jeans_m_2;
        case 'asset.jeans_m_3':
            return asset.jeans_m_3;
        case 'asset.jeans_m_4':
            return asset.jeans_m_4;
        case 'asset.jeans_m_5':
            return asset.jeans_m_5;
        case 'asset.jeans_m_6':
            return asset.jeans_m_6;
        case 'asset.jeans_m_7':
            return asset.jeans_m_7;
        case 'asset.jeans_m_8':
            return asset.jeans_m_8;
        case 'asset.jeans_m_9':
            return asset.jeans_m_9;
        case 'asset.jeans_m_10':
            return asset.jeans_m_10;
        case 'asset.jeans_m_11':
            return asset.jeans_m_11;
        case 'asset.jeans_m_12':
            return asset.jeans_m_12;
        case 'asset.jeans_m_13':
            return asset.jeans_m_13;
        case 'asset.jeans_w_1':
            return asset.jeans_w_1;
        case 'asset.jeans_w_2':
            return asset.jeans_w_2;
        case 'asset.jeans_w_3':
            return asset.jeans_w_3;
        case 'asset.jeans_w_4':
            return asset.jeans_w_4;
        case 'asset.jeans_w_5':
            return asset.jeans_w_5;
        case 'asset.jeans_w_6':
            return asset.jeans_w_6;
        case 'asset.jeans_w_7':
            return asset.jeans_w_7;
        case 'asset.jeans_w_8':
            return asset.jeans_w_8;
        case 'asset.jeans_w_9':
            return asset.jeans_w_9;
        case 'asset.jeans_w_10':
            return asset.jeans_w_10;
        case 'asset.jeans_w_11':
            return asset.jeans_w_11;
        case 'asset.jeans_w_12':
            return asset.jeans_w_12;
        case 'asset.shirt_m_1':
            return asset.shirt_m_1;
        case 'asset.shirt_m_2':
            return asset.shirt_m_2;
        case 'asset.shirt_m_3':
            return asset.shirt_m_3;
        case 'asset.shirt_m_4':
            return asset.shirt_m_4;
        case 'asset.shirt_m_5':
            return asset.shirt_m_5;
        case 'asset.shirt_m_6':
            return asset.shirt_m_6;
        case 'asset.shirt_m_7':
            return asset.shirt_m_7;
        case 'asset.shirt_m_8':
            return asset.shirt_m_8;
        case 'asset.shirt_m_9':
            return asset.shirt_m_9;
        case 'asset.shirt_m_10':
            return asset.shirt_m_10;
        case 'asset.shirt_m_11':
            return asset.shirt_m_11;
        case 'asset.shirt_m_12':
            return asset.shirt_m_12;
        case 'asset.shirt_w_1':
            return asset.shirt_w_1;
        case 'asset.shirt_w_2':
            return asset.shirt_w_2;
        case 'asset.shirt_w_3':
            return asset.shirt_w_3;
        case 'asset.shirt_w_4':
            return asset.shirt_w_4;
        case 'asset.shirt_w_5':
            return asset.shirt_w_5;
        case 'asset.shirt_w_6':
            return asset.shirt_w_6;
        case 'asset.shirt_w_7':
            return asset.shirt_w_7;
        case 'asset.shirt_w_8':
            return asset.shirt_w_8;
        case 'asset.shirt_w_9':
            return asset.shirt_w_9;
        case 'asset.shirt_w_10':
            return asset.shirt_w_10;
        case 'asset.shirt_w_11':
            return asset.shirt_w_11;
        case 'asset.shirt_w_12':
            return asset.shirt_w_12;
        case 'asset.accessories_1':
            return asset.accessories_1;
        case 'asset.accessories_2':
            return asset.accessories_2;
        case 'asset.accessories_3':
            return asset.accessories_3;
        case 'asset.accessories_4':
            return asset.accessories_4;
        case 'asset.accessories_5':
            return asset.accessories_5;
        case 'asset.accessories_6':
            return asset.accessories_6;
        case 'asset.accessories_7':
            return asset.accessories_7;
        case 'asset.accessories_8':
            return asset.accessories_8;
        case 'asset.accessories_9':
            return asset.accessories_9;
        case 'asset.accessories_10':
            return asset.accessories_10;
        case 'asset.accessories_11':
            return asset.accessories_11;
        case 'asset.accessories_12':
            return asset.accessories_12;
        case 'asset.accessories_13':
            return asset.accessories_13;
        case 'asset.accessories_14':
            return asset.accessories_14;
        case 'asset.accessories_15':
            return asset.accessories_15;
        case 'asset.dress1':
            return asset.dress1;
        case 'asset.dress2':
            return asset.dress2;
        case 'asset.dress3':
            return asset.dress3;
        case 'asset.dress4':
            return asset.dress4;
        case 'asset.dress5':
            return asset.dress5;
        case 'asset.dress6':
            return asset.dress6;
        case 'asset.dress7':
            return asset.dress7;
        case 'asset.dress8':
            return asset.dress8;
        case 'asset.dress9':
            return asset.dress9;
        case 'asset.dress10':
            return asset.dress10;
        case 'asset.dress11':
            return asset.dress11;
        case 'asset.dress12':
            return asset.dress12;
        case 'asset.skirts_1':
            return asset.skirts_1;
        case 'asset.skirts_2':
            return asset.skirts_2;
        case 'asset.skirts_3':
            return asset.skirts_3;
        case 'asset.skirts_4':
            return asset.skirts_4;
        case 'asset.skirts_5':
            return asset.skirts_5;
        case 'asset.skirts_6':
            return asset.skirts_6;
        case 'asset.skirts_7':
            return asset.skirts_7;
        case 'asset.skirts_8':
            return asset.skirts_8;
        case 'asset.skirts_9':
            return asset.skirts_9;
        case 'asset.skirts_10':
            return asset.skirts_10;
        case 'asset.skirts_11':
            return asset.skirts_11;
        case 'asset.skirts_12':
            return asset.skirts_12;
    }
}
